services:
  rabbitmq:
    image: registry.hub.docker.com/library/rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins

configs:
  rabbitmq-plugins:
    content: |
      [rabbitmq_management].

